services:
  app:
    # image: ruby:3.4.1
    build:
      target: dev
    command: ['rails', 'server', '--port=3000', '--binding=0.0.0.0']
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      # - 127.0.0.1:3000:3000
      - 3000:3000
  # vite:
  #   build:
  #     target: dev
  #   command: ['bin/vite', 'dev']
  #   volumes:
  #     - ./:/app
  #     - bundle:/usr/local/bundle
  #     - node_modules:/app/node_modules
  #   working_dir: /app
  mongo:
    image: mongo:8.0.4

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
