services:
  app:
    # image: ruby:3.4.1
    build:
      target: dev
    command: ['rails', 'server', '--port=3000', '--binding=0.0.0.0']
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      # - 127.0.0.1:3000:3000
      - 3000:3000
    depends_on:
      - mongo
  # vite:
  #   build:
  #     target: dev
  #   command: ['bin/vite', 'dev']
  #   volumes:
  #     - ./:/app
  #     - bundle:/usr/local/bundle
  #     - node_modules:/app/node_modules
  #   working_dir: /app
  mongo:
    image: mongo:8.0.4

  # docker compose cp caddy:/data/caddy/pki/authorities/local/root.crt .
  caddy:
    image: caddy
    ports:
      - 0.0.0.0:3011:3011
      # - '127.0.0.1:3011:3011'
      # - '127.0.0.1:3036:3036'
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
  caddy_data:
    driver: local
