apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: attic
  name: attic
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: attic
    spec:
      serviceAccountName: attic
      containers:
        - command:
            - ./bin/rails
            - server
            - -p
            - "3010"
            - -e
            - production
          image: us-west1-docker.pkg.dev/topics-server/attic/attic:${TAG}
          name: attic
          ports:
            - containerPort: 3010
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /rails/config/master.key
              name: master-key
              subPath: master.key
      volumes:
        - name: master-key
          secret:
            secretName: attiq-master-key
        # - csi:
        #     driver: secrets-store-gke.csi.k8s.io
        #     readOnly: true
        #     volumeAttributes:
        #       secretProviderClass: attic-master-key
        #   name: master-key
