apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: attiq
  name: attiq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attiq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: attiq
    spec:
      containers:
        - command:
            - ./bin/rails
            - server
            - -p
            - "3010"
            - -e
            - production
          image: ${IMAGE}:${TAG}
          name: attiq
          ports:
            - containerPort: 3010
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /rails/config/master.key
              name: master-key
              subPath: master.key
      volumes:
        - name: master-key
          secret:
            secretName: attiq-master-key
